### ISSUE TITLE
ElixirLS Crashing

### ISSUE THREAD

**Issue by nessun-dorma** [kabinspace/AstroVim#264] opened 2022-04-08 14:36 UTC
![image](https://user-images.githubusercontent.com/96528048/162458415-ee0e5277-3a35-47ac-afb3-ca1db5bb760b.png)
I've installed dartls along with elixirls and dartls works fine. I don't know what is wrong with ElixirLS. Is it Astro related bug ??

**Comment by mehalter** [comment] 2022-04-08 15:57
Could you check the LSP and lsp-installer logs in `~/.cache/nvim/lsp.log` and `~/.cache/nvim/lsp-installer.log`. I believe the information you are looking  for will be in the `lsp.log`. It should show why the server is crashing.

**Comment by mehalter** [comment] 2022-04-08 16:03
I would also try running `~/.local/share/nvim/lsp_servers/elixir-ls/language_server.sh` manually and see if the script is able to run

**Comment by mehalter** [comment] 2022-04-08 16:12
I just tried to install it with AstroVim and noticed that I also got crashing initially and it was due to me not having `elixir` installed. Could that be the reason? Once I installed `elixir` and had it in my path the LSP started up perfectly.

**Comment by nessun-dorma** [comment] 2022-04-08 16:28
`[INFO  Fri 08 Apr 2022 07:59:10 PM IST] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:668: Starting install server_name="eslint", requested_version=""
[ERROR Fri 08 Apr 2022 07:59:10 PM IST] ...installer/lua/nvim-lsp-installer/core/installer/init.lua:48: Installation failed, name="eslint", error={
  exit_code = 127,
  <metatable> = {
    __tostring = <function 1>
  }
}
[INFO  Fri 08 Apr 2022 07:59:10 PM IST] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:687: Installation completed server_name="eslint", success=false
[INFO  Fri 08 Apr 2022 08:00:30 PM IST] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:668: Starting install server_name="dartls", requested_version=""
[INFO  Fri 08 Apr 2022 08:00:30 PM IST] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:687: Installation completed server_name="dartls", success=true
[INFO  Fri 08 Apr 2022 08:01:21 PM IST] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:668: Starting install server_name="elixirls", requested_version=""
[ERROR Fri 08 Apr 2022 08:01:21 PM IST] ...pt/nvim-lsp-installer/lua/nvim-lsp-installer/process.lua:153: Failed to spawn process. cmd="gh", err="ENOENT: no such file or directory"
[INFO  Fri 08 Apr 2022 08:01:24 PM IST] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:687: Installation completed server_name="elixirls", success=true
[ERROR Fri 08 Apr 2022 08:03:09 PM IST] ...er/lua/nvim-lsp-installer/jobs/outdated-servers/init.lua:78: Unable to find checker for source="system"
[ERROR Fri 08 Apr 2022 08:03:09 PM IST] ...pt/nvim-lsp-installer/lua/nvim-lsp-installer/process.lua:153: Failed to spawn process. cmd="gh", err="ENOENT: no such file or directory"`

The output of `cat lsp-installer.log`

**Comment by nessun-dorma** [comment] 2022-04-08 16:29
```
[START][2022-04-08 19:53:56] LSP logging initiated
[START][2022-04-08 19:56:19] LSP logging initiated
[START][2022-04-08 19:56:32] LSP logging initiated
[START][2022-04-08 19:58:39] LSP logging initiated
[START][2022-04-08 20:02:03] LSP logging initiated
[START][2022-04-08 20:02:50] LSP logging initiated
[START][2022-04-08 20:05:03] LSP logging initiated
[START][2022-04-08 20:35:20] LSP logging initiated
[START][2022-04-08 20:35:44] LSP logging initiated
[START][2022-04-08 20:10:06] LSP logging initiated
[START][2022-04-08 21:55:15] LSP logging initiated
```
The Output of `cat lsp.log`

**Comment by nessun-dorma** [comment] 2022-04-08 16:30
I can't find anything relevant to my issue in these log files.

**Comment by mehalter** [comment] 2022-04-08 17:01
This bug is coming from the LSP server configuration in some way and is not related to  the AstroVim configuration. I would start by setting: `vim.lsp.set_log_level("debug")` in your `init.lua` in the `polish()` function to enable LSP debug level logging and then recheck back at `lsp.log` to see if you can get any more information. Based on the message you are getting your Elixir language server is crashing while running for some reason which is a separate process from Neovim all together.

**Comment by mehalter** [comment] 2022-04-08 17:45
I'm going to go ahead and close this since it is not related to AstroVim in particular. If you figure out what the problem is please drop some pointers or tips back in this issue if a future user runs into a similar problem.

**Closed by mehalter** 2022-04-08 17:45 UTC
