### ISSUE TITLE
Bufferline (tabs) hidden in nvim-qt NVUI Goneovim

### ISSUE THREAD

**Issue by kden416** [kabinspace/AstroVim#49] opened 2022-02-11 18:39 UTC
So, no GUI tabs, no terminal tabs. If i disable neovim-qt tabs, does not matter, terminal tabs (bufferline) will not shown.

**Comment by kden416** [comment] 2022-02-11 18:40
Oh,,,in terminal nvim, tabs shown fine.

**Comment by kabinspace** [comment] 2022-02-11 18:42
Yes, it is only aimed for terminal, not the qt version

**Comment by kden416** [comment] 2022-02-11 18:45
how can i disable bufferline? I have no gui tabs too in this applications (with bufferline enabled)

**Comment by kabinspace** [comment] 2022-02-11 18:47
@kabinspace You need to go [here](https://github.com/kabinspace/AstroVim/blob/ca89aa314bd487f8e5fc0568edbc2f0b1865acc4/lua/user/settings.lua#L33) and set it to `false` and do `:PackerSync` to disable it. Please check out user [guide](https://github.com/kabinspace/AstroVim/blob/main/utils/userguide.md) for more info

**Comment by kabinspace** [comment] 2022-02-11 18:49
@kden416 Your question sounds very confusing, you want GUI tabs but you also want to disable bufferline? Bufferline is responsible for those GUI tabs.

**Comment by kden416** [comment] 2022-02-11 18:59
Ok, im confused. I have problem with tabs in neovim-qt:
- tabs in neovim-qt won't work
- tabs in neovim (terminal) works fine with AstroVim config
- with disabled bufferline changes nothing
- I need any tabs in GUI applications (e.g. neovim-qt)

**Comment by kabinspace** [comment] 2022-02-11 19:13
@kden416 Sorry, but AstroVim was only aimed for the stable terminal version, I haven't tested AstroVim for any other versions like neovim-qt, nightly, etc. I can't really provide any support in this case.

**Comment by kabinspace** [comment] 2022-02-11 19:31
Though you can open an issue if you get any problems with the terminal version. Since you are saying it is working fine in the terminal, I am going to close the issue.

**Closed by kabinspace** 2022-02-11 19:31 UTC

**Comment by kden416** [comment] 2022-02-12 08:40
Problem was solved.
Dashboard plugin, at application startup disables tabline, and then tabline hidden all time.
But if i start app, bypassing dashboard, tabline works fine. Same, if dashboard disabled.

**Comment by LittleSheep2Code** [comment] 2022-05-02 09:54
I think you need disable the ui feature on init.lua, like this:
```lua
vim.opt.rtp:append(vim.fn.stdpath "config" .. "/../astronvim")

local impatient_ok, impatient = pcall(require, "impatient")
if impatient_ok then
  impatient.enable_profile()
end

local utils = require "core.utils"

utils.disabled_builtins()

utils.bootstrap()

local sources = {
  "core.options",
  "core.plugins",
  "core.autocmds",
  "core.mappings",
  "configs.which-key-register",
}

for _, source in ipairs(sources) do
  local status_ok, fault = pcall(require, source)
  if not status_ok then
    error("Failed to load " .. source .. "\n\n" .. fault)
  elseif source == "core.plugins" then
    utils.compiled()
  end
end

-- local status_ok, ui = pcall(require, "core.ui")
-- if status_ok then
--   for ui_addition, enabled in pairs(utils.user_settings().ui) do
--     if enabled and type(ui[ui_addition]) == "function" then
--       ui[ui_addition]()
--     end
--   end
-- end

local polish = utils.user_plugin_opts "polish"
if type(polish) == "function" then
  polish()
end
```

**Comment by mehalter** [comment] 2022-05-02 12:23
@LittleSheep2Code this can be done without editing the core files inside your `user/init.lua` file. Here is a minimal `user/init.lua` file that disables the UI stuff:

```lua
return {
  ui = {
    nui_input = false,
    telescope_select = false,
  },
}
```

**Comment by LittleSheep2Code** [comment] 2022-05-02 12:25
> 

I tried, but it still need run packer compile

**Comment by mehalter** [comment] 2022-05-02 12:27
I'm not sure I follow. What is the bug here?

**Comment by LittleSheep2Code** [comment] 2022-05-02 12:30
I disable all ui option in the user/init.lua and I still need reload to active it like this
![Example](https://user-images.githubusercontent.com/56875315/166233789-45347fa0-5c61-49da-bca2-18cd910192c6.gif)

**Comment by mehalter** [comment] 2022-05-02 12:32
ah interesting, this shouldn't be related to the `ui` code. Were you saying if you comment out that block as you did in your previous comment this fixes it?

**Comment by LittleSheep2Code** [comment] 2022-05-02 12:33
Nope, it still need packer compile

**Comment by mehalter** [comment] 2022-05-02 12:33
Ok, that's what I figured. The ui stuff shouldn't be affecting that. That's good at least

**Comment by mehalter** [comment] 2022-05-02 12:35
AstroNvim is built specifically to not show the statusbar and bufferline on the dashboard in particular. So when the buffer is loaded they are removed. The same in the terminal. When you run the PackerCompile you are short circuiting those autocommands and resetting the UI.

**Comment by LittleSheep2Code** [comment] 2022-05-02 12:37
I known this, but....... In the other buffer, it isn't show that!
![Example](https://user-images.githubusercontent.com/56875315/166234578-7497e1f2-983b-4e9e-a420-b26cdac86b74.gif)

**Comment by mehalter** [comment] 2022-05-02 12:37
once you leave the dashboard and open a file or something the statusbar and bufferline should come back. This behavior can be disabled with this in your `user/init.lua` file:

```lua
return {
  polish = function()
    vim.api.nvim_del_augroup_by_name "dashboard_settings"
  end,
}
```

But this is not a bug, but a feature to make the Dashboard look cleaner and less cluttered.

**Note** We are about to merge a PR that moves from Dashboard to Alpha.nvim because Dashboard is no longer maintained or updated and also Alpha.nvim is written in lua so the above code will become:

```lua
return {
  polish = function()
    vim.api.nvim_del_augroup_by_name "alpha_settings"
  end,
}
```

**Comment by mehalter** [comment] 2022-05-02 12:39
Ah I see what you mean now @LittleSheep2Code sorry, I thought the confusion was different from your first screenshare. You could try the above autogroup deletes in your polish function and see if that fixes it. I wonder if Neovide changes how buffer loading is detected and happening

**Comment by LittleSheep2Code** [comment] 2022-05-02 12:40
Great! It fix it, but I tried in goneovim, it still didn't show.

**Comment by mehalter** [comment] 2022-05-02 12:41
Also We just merged the latest changes with `Alpha.nvim` migration. Could you try the latest commit without disabling the autogroup and see if that has any different behavior? @LittleSheep2Code

**Comment by LittleSheep2Code** [comment] 2022-05-02 13:16
Yes, it fixed it! :)

**Comment by mehalter** [comment] 2022-05-02 13:27
Awesome, this may have been a bug in the Dashboard plugin all together. Glad to see that's fixed.
