### ISSUE TITLE
Undocumented window management mappings

### ISSUE THREAD

**Issue by sbeyer** [kabinspace/AstroVim#191] opened 2022-03-23 16:43 UTC
Hi,

I'm using AstroVim for the first day so some things just don't work as expected.

A mapping I often use is `C-w s` which does the same as `:split`.
Another mapping I sometimes use is `C-w T` which moves the current window into a new tab.
Yet another mapping is `C-w =` that resets all window sizes such that they are evenly split.
All those do not work any longer with AstroVim and I can't find a replacement (for example, switching between windows got a nice replacement mapping).

Two question:
1. Is it intentional or a bug that those do not work any longer? (edit: I just noticed that `C-w` saves the buffer, so it's probably not intentional... ~~however `C-w <cursor>` resizes successfully~~ edit2: it's `C-<cursor>`, nevermind)
1. Is there a replacement? How can I find out the replacements without asking someone? (e.g. `:help split` shows the original mappings that do not work)

**Comment by mehalter** [comment] 2022-03-23 16:48
Thanks for the feedback. I agree that `<c-w>` is a key binding. Astrovim rebinds this to force save the current file by default. This can be fixed by adding the following in your `polish()` function in the `user/init.lua` file:

```lua
vim.api.nvim_del_keymap("n", "<c-w>")
```

**Comment by sbeyer** [comment] 2022-03-23 17:00
Thanks. However, this does simply remove the `C-w` functionality altogether, so the "force write" functionality is gone, but the original `C-w` functionality is not restored. As a temporary workaround I commented out the `C-w` mapping in `lua/core/mappings.lua`

**Comment by mehalter** [comment] 2022-03-23 17:07
Hm, I have am using that `nvim_del_keymap` to remove the `<c-w>` binding and it should set it back to the default behavior in neovim (as per the  neovim documentation). I can confirm that after this line is in my `polish` function in `user/init.lua`:

```lua
  local unmap = function(mode, shortcut)
    vim.api.nvim_del_keymap(mode, shortcut)
  end
  local nunmap = function(shortcut)
    unmap("n", shortcut)
  end
  nunmap "<C-w>"
```

I do get the original behavior back with `<c-w>s` for example to split and `<c-w>T` for moving a split to a new tab. This has been confirmed both in my user config and the stock AstroVim with this as the entire `init.lua` file:

```lua
return {
  polish = function()
    vim.api.nvim_del_keymap("n", "<C-w>")
  end,
}
```

@sbeyer if this is not working in your `user/init.lua` could you please send your entire `init.lua` so we can figure out what is wrong with it? :)

**Comment by mehalter** [comment] 2022-03-23 17:08
accidentally closed before we got a resolution to the `user/init.lua`

**Comment by mehalter** [comment] 2022-03-23 17:18
We have changed this binding to be a more sane default to `<ctrl-s>`, but for future reference. The `del_keymap` function does make the keybinding perform as default.

**Comment by sbeyer** [comment] 2022-03-23 17:19
I used your example now and it works. I guess there was a syntax error in my `user/init.lua`. Interstingly, nvim does not complain at startup when there are syntax errors in user.lua ... would it make sense to replace the `pcall(require, "user")` by a hard `require "user"` in `lua/core/utils.lua`?

**Comment by sbeyer** [comment] 2022-03-23 17:19
Wow you are really quick with closing issues.

**Closed** 2022-03-23 17:19 UTC

**Comment by mehalter** [comment] 2022-03-23 17:38
@sbeyer I agree it would be nice for there to be a notice. The problem is the `init.lua` file isn't required for running the default setup nor for customization in the `user/` folder so it becomes difficult to verify. We could add a check to see if  the file `init.lua` exists and if there is an error when loading it. It just wouldn't be an exhaustive test for when people don't use the `init.lua` file
